run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  tests: false
  build-tags:
    - mytag
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true
  go: '1.22'

output:
  formats:
    - format: colored-line-number
      path: stdout
    - format: json
      path: report.json

linters:
  enable:
    - errcheck
    - govet
    - gocyclo
    - gofmt
    - goimports
    - ineffassign
    - megacheck
    - nakedret
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  gofmt:
    simplify-imports: true
  golint:
    min-confidence: 0.8
  govet:
    check-shadowing: true