version: '3'

services:
  image_service:
    container_name: image_service
    build: 
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ".dev.env"
    environment:
      MINIO_HOST: minio # переопределяем, потому что находимся в сети Docker
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - minio

  minio:
    container_name: minio
    image: bitnami/minio:latest
    volumes:
      - minio-storage:/bitnami/minio/data
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    env_file:
      - ".dev.env"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_USE_SSL: "${MINIO_USE_SSL}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio-storage: