FROM golang:1.22-alpine AS build
WORKDIR /app
COPY go.mod go.sum .
RUN go mod download
COPY cmd /app/cmd
COPY internal /app/internal
RUN go build -o main cmd/main.go

FROM alpine:latest
WORKDIR /app
RUN apk --no-cache add ca-certificates
COPY --from=build /app/main .
EXPOSE 8080
CMD ["./main"]