FROM golang:1.22.1 AS build
WORKDIR /app
COPY go.mod go.sum .
RUN go mod download
COPY cmd /app/cmd
COPY internal /app/internal
RUN go build -o main cmd/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=build /app/main .
EXPOSE 8080
CMD ["./main"]